# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct

export PATH=$PATH:/usr/local/aseprite
export PATH=$PATH:/usr/local/godot
export PATH=$PATH:/usr/local/nvim/nvim-linux-x86_64/bin
